platform :ios, '5.0'
inhibit_all_warnings!

xcodeproj 'Example Project'
workspace 'Example Project'

pod 'ObjectiveLuhn', :path => '../ObjectiveLuhn.podspec'

target :Tests, :exclusive => true do
  pod 'Kiwi/XCTest'
end
